### ISSUE TITLE
Create a Logo for the App

### ISSUE THREAD

**Issue by prasadhonrao** [prasadhonrao/mern-bootcamp#8]
**Description**:
We need to design a logo for the MERN Bootcamp application. A professional and visually appealing logo will help establish the brand identity of the application and enhance its visual appeal.

**Task**:
1. **Design Requirements**:
   - The logo should reflect the purpose of the MERN Bootcamp application, which is to help users find, rate, and review coding bootcamps.
   - The design should be clean, modern, and scalable for use in various contexts (website, mobile app, marketing materials).
   - The logo should include the application name or an icon that represents coding or bootcamps.

2. **Deliverables**:
   - A primary logo design in vector format (e.g., SVG) to ensure scalability.
   - Additional formats for use in different contexts (e.g., PNG, JPEG).
   - A favicon version of the logo for use in browser tabs.

3. **Implementation**:
   - Once the logo is finalized, update the application with the new logo

**Acceptance Criteria**:
- A final logo design is created and approved by the team.
- The logo is provided in vector format (SVG) and additional formats (PNG, JPEG).
- A favicon version of the logo is created.
- The logo is implemented in the application and associated marketing materials.

**References**:
- [Logo Design Inspiration](https://dribbble.com/)
- [Favicon Generator](https://www.favicon-generator.org/)
- [Logo Design Best Practices](https://www.smashingmagazine.com/2017/03/creating-logotypes-part-1/)

**Comment by sakharesoham** [comment]
Hello Team,
I have attached a compressed folder containing the finalized logo design. It includes colorful, light-themed, and dark-themed logos, as well as favicons.
[Final_Logo_Design.zip](https://github.com/user-attachments/files/16929637/Final_Logo_Design.zip)

**Comment by prasadhonrao** [comment]
Thanks @sakharesoham, looks really good! Can you create a PR and submit it please?

**Comment by sakharesoham** [comment]
Hello @prasadhonrao, I have created a pull request for the same and contributed to the repository. Please check if it's reflecting in the main branch.
Thank you.

**Comment by prasadhonrao** [comment]
@sakharesoham you can not directly merge into the main branch as it is protected. You need to fork the repository using your GitHub account, make the changes in your repo and then submit the PR so that I can merge the changes from your repository to mine. Check out few YouTube videos or use ChatGPT for help otherwise I will explain during our next meeting.

**Comment by sakharesoham** [comment]
Hello @prasadhonrao , I have submitted the PR and added logos to new folder 'ux'.
